tex:
  template: tufte-handout.template
  replace: 
    - "figure}.*": "marginfigure}"
evalsOptions:
  - graph.output: pdf
  - graph.unify: true
  - cache: false
panderOptions:
  - graph.background: white
  - graph.grid: false
  - graph.grid.minor: false
  - graph.legend.position: bottom
